name: Code Coverage (Javascript)

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'
      
  pull_request:
    branches:
      - main
    paths:
      - '**/*.js'

  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  test:
    name: Run Tests and Upload Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version (v3)

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '14'

      - name: Install Jest globally
        run: |
          npm install -g jest  # Install Jest globally

      - name: Create Jest config file dynamically
        run: |
          echo "module.exports = {
            roots: ['<rootDir>/'],
            testMatch: ['**/*.test.js'],  
            collectCoverage: true,
            coverageDirectory: 'coverage',
            coverageReporters: ['html', 'text', 'lcov'] 
          };" > jest.config.js

      - name: Run tests with coverage
        run: |
          # Run Jest with coverage and the dynamically created config file
          jest --config=jest.config.js --coverage --passWithNoTests --coverageDirectory=coverage 

      - name: Upload Coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Javascript_coverage
          path: coverage/

      - name: Clean up coverage directory
        run: rm -rf coverage/  
