    - name: Create `docs/` Folder and Replace User Folder with New Report
      run: |
        # Set a custom username instead of using GITHUB_ACTOR
        USERNAME="custom-username"

        # Define the path for the user's folder in the docs directory
        DOCS_FOLDER="docs/$USERNAME"

        # Create the docs directory if it doesn't exist
        mkdir -p "$DOCS_FOLDER"
        
        # Move the newly generated ESLint report to the user's folder in docs/
        if [ -f "eslint-report.html" ]; then
          mv eslint-report.html "$DOCS_FOLDER/"
        else
          echo "ESLint report not found. Exiting."
          exit 1
        fi

    - name: Commit and Push Updated Report to GitHub Pages
      run: |
        # Add and commit the updated report to the repository
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Add the file if it exists
        if [ -f "docs/$USERNAME/eslint-report.html" ]; then
          git add docs/$USERNAME/eslint-report.html
          git commit -m "Update ESLint report for $USERNAME"
          
          # Push the changes to the repository
          git push origin main --force
        else
          echo "No report to commit. Skipping."
        fi
